### ISSUE TITLE
When I load the zip file for installation, I get the following error message

### ISSUE THREAD

**Issue by Winnies31** [seven-io/dolibarr#1]
Good morning,
When I load the zip file for installation, I get the following error message:
_The module package appears to have the wrong format.
At least one mandatory folder must be present in the module's zip archive: sevenio or htdocs/sevenio_
Can we install the module differently on dolibarr?
I thank You

**Comment by matthiez** [comment]
Hi @Winnies31,
thanks for reporting. There was missing a directory. Please try again with [2.0.0](https://github.com/seven-io/dolibarr/releases/tag/2.0.0). It should work now.

**Comment by Winnies31** [comment]
Thanks, the module installation worked.
