### ISSUE TITLE
DOLIBARR cannot find an SMS module 

### ISSUE THREAD

**Issue by Winnies31** [seven-io/dolibarr#2]
Hello,
I successfully installed the SMS module, but then DOLIBARR cannot find an SMS module to use it
Thank's
Nicolas
![find-module](https://github.com/seven-io/dolibarr/assets/38534099/7ba7f966-1d82-499a-8937-96d78d3e563e)

**Comment by matthiez** [comment]
Hi @Winnies31,
sorry for the late reply.

As of now, our module doesn't make use of the built-in SMS functionality.
However, we are working on supporting it. Please watch this repository for updates.

**Comment by matthiez** [comment]
Hi @Winnies31,
please try upgrading to [v2.1.0](https://github.com/seven-io/dolibarr/releases/tag/2.1.0) and see if that works for you.

Hope this helps!
